### ISSUE TITLE
USD plug-in for Maya on Windows

### ISSUE THREAD

**Issue by krzykli** [vfxpro99/usd-build-club#10]
Not an issue really but a question.

Which versions of Maya (if any) have been proven to work with USD Maya plug-in on Windows?

Thanks,
kk

**Comment by vfxpro99** [comment]
AFAIK Maya2017, haven't heard of anyone trying it on 2016 or earlier.

**Comment by krzykli** [comment]
Thanks @vfxpro99,
I've just compiled the plug-in against 2016.5 and 2017 and in both cases when loading it I get the following error:
`Error: line 1: Unable to dynamically load : C:/path/to/pxrUsd.mll`
I didn't have any errors during compilation, everything went really smoothly, yet something is clearly wrong. When inspecting the .mll file I can see some lines say `API error detected`.

I'm running Windows 7 and the latest VS 2015 Community.

**Comment by vfxpro99** [comment]
Have you set up the environment variables as in setvars-windows.cmd? You may also need to set up PXR_PLUGINPATH_NAME=c:/path/to/share/usd/plugins/

**Comment by krzykli** [comment]
Yes, my environment is correct, adding `PXR_PLUGINPATH_NAME` didn't change much unfortunately. The thing that concerns me though is that in the .mll file itself, after opening it with a text editor, among all the gibberish there are lines clearly saying `API error detected`. This is quite odd because I got no compilation errors whatsoever... I'll keep digging :)

**Comment by krzykli** [comment]
Somebody else has hit the same issue:
https://groups.google.com/forum/#!topic/usd-interest/_kk4prgIpzI

**Comment by vfxpro99** [comment]
Ah, that is fantastic information. It looks like a fix is to pin the Maya plugin build to glew 1.10.0

Hey,
It should compile with glew 1.10.0. glew 1.11.0 adds support for OpenGL 4.5. The missing symbols are used in USD\pxr\imaging\lib\hd\renderContextCaps.cpp lines 195:199. You can compile it with correct glew version or just delete this lines

Adrian

**Comment by RiggestOu** [comment]
it can work in Maya 2016.5

**Comment by vfxpro99** [comment]
It's also necessary to pin the Ptex version to 2.0.22. @krzykli Did you eventually get the Maya build working? I ran into a bunch of HDF5 issues building the UsdAbc plugin, so manually stripped out HDF5 support, and got it working.

**Comment by krzykli** [comment]
Yes, after removing GLUT dependency and replacing Maya's glew.dll with the one I compiled UsdMaya against the build was working fine and I could load the plug-in. That's been a while ago though, I haven't had time recently to check out the new improvements to the Windows port. I hope by the time I go back to exploring USD the build process will be super smooth :)

**Comment by meshula** [comment]
The build script in the USD repo does a great job of building USD for Maya out of the box, so I'm closing this issue. Feel free to reopen if you feel there's more to pursue here.
